baseURL: "https://mjvo.github.io/vms202d"
title: "VMS 202D"

defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1

MetaDataFormat: "yaml"

theme: 
  - "hugo-course"
  - "reveal-hugo"

FootnoteReturnLinkContents: "↩"

outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
  Remark:
    baseName: index
    mediaType: text/html
    isHTML: true
  
params:
  course:
    name: "Introduction to Visual Culture"
    dept_url: "https://aahvs.duke.edu"
    dept_logo: "/images/AAHVS_Barcode_Logo.png"
    day_time: "Mondays & Wednesdays, 10:05 - 11:20 AM"
    location: "A266 Smith Warehouse, Bay 10"
    hero_img: "/images/graffiti_art.jpg"
    hero_img_credit: "Image: <a href=\"https://www.flickr.com/photos/freefoto/15836467154\">Graffiti Art</a> by <a href=\"https://www.flickr.com/photos/freefoto/\">Ian Britton</a>, 2015"

  reveal_hugo:
    theme: white
    
    width: 960
    height: 540
    margin: 0.1
    min_scale: .1
    max_scale: 1

    highlight_theme: "atom-one-dark"